services:
  redis:
    image: redis:7-alpine
    container_name: flash-sale-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  k6:
    image: grafana/k6
    profiles: ["loadtest"]
    volumes:
      - ./loadtest:/scripts
    command: run /scripts/seckill.js
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: flash-sale-rabbitmq
    ports:
      - "5672:5672"      # app connection
      - "15672:15672"    # management interface
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5      

volumes:
  redis-data:

