spring:
  application:
    name: flash_sale_system
  datasource:
    url: jdbc:postgresql://localhost:5432/flash_sale
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  #for test concurrency: false
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    listener:
      simple:
        concurrency: 5              # 5 consumer threads
        prefetch: 10                # Each consumer can prefetch up to 10 messages
        default-requeue-rejected: false   # Failed messages are not requeued, but sent to the dead-letter queue
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 500ms

server:
    port: 8081
